GMM:
  autotune: False
  name_of_backend_to_use: "cuda"
  template_path: "/home/haria/pycasp/specializers/gmm/"
  cuda_device_id: 0
SVM:
  autotune: False
  name_of_backend_to_use: "cuda"
  template_path: "/home/haria/pycasp/specializers/svm/"
  cuda_device_id: 0
